language: java
jdk:
  - oraclejdk8

install: gradle assemble

// build.gradle
apply plugin: "java"
sourceCompatibility = 1.8
repositories {
    mavenCentral()
}
dependencies {
    testCompile 'junit:junit:4.11'
    testCompile 'org.mockito:mockito-core:1.9.+'
}
#deploy:
#  provider: heroku
#  api_key:
#    secure: "f56065ae-df68-4448-9689-cedee23744dc"