language: java
install: gradle assemble

dependencies {
    testCompile 'junit:junit:4.11'
    testCompile 'org.mockito:mockito-core:1.9.+'
}
#deploy:
#  provider: heroku
#  api_key:
#    secure: "f56065ae-df68-4448-9689-cedee23744dc"
