language: java
jdk:
  - oraclejdk8

#install: gradle check

script:
  - ./gradlew clean build test check

cache:
  directories:
  - $HOME/.m2

deploy:
  provider: heroku
  api_key:
    secure: "f56065ae-df68-4448-9689-cedee23744dc"