language: java

install: gradle check

script:
# Display Gradle, Groovy, JVM and other versions
  - ./gradlew --version
  
# Build JUnit 5
  - ./gradlew ${SCAN} build ${INSTALL}


cache:
  directories:
  - $HOME/.m2

deploy:
  provider: heroku
  api_key:
    secure: "f56065ae-df68-4448-9689-cedee23744dc"